### ISSUE TITLE
Development Env. is broken

### ISSUE THREAD

**Issue by mustafaileri** [datacontract/datacontract-cli#329] opened 2024-07-16 13:03 UTC
Hello, I have just cloned your repo to my local to contribute. I follow the instructions to set up from README.
I got this error message when I run pytest:
`
(venv) ☁  datacontract-cli [main] pytest
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
  inifile: /Users/mileri/Code/datacontract-cli/pyproject.toml
  rootdir: /Users/mileri/Code/datacontract-cli
`
My Python version is: Python 3.11.9

Suggestion: Also it would be great to manage it via poetry.

You can consider this or if only I have this problem; please feel free to close this ticket. I can find another way to run to locally ;)

**Comment by jochenchrist** [comment] 2024-07-16 13:20
Was `pip install -e '.[dev]'` successful?

The `-n` comes from `pytest-xdist` to run tests in parallel, that should be included with the dev extra.

**Comment by mustafaileri** [comment] 2024-07-16 13:47
Yes, it was. As far as I see everything worked smoothly.

**Comment by jochenchrist** [comment] 2024-07-18 15:14
Anyone else having this issue?

**Comment by jochenchrist** [comment] 2024-08-10 16:57
Closing as cannot reproduce.

**Closed by jochenchrist** 2024-08-10 16:57 UTC
Labels: invalid
