### ISSUE TITLE
Add support for TIMESTAMP type in duckdb

### ISSUE THREAD

**Issue by RobertLD** [datacontract/datacontract-cli#472] opened 2024-10-18 18:04 UTC
https://github.com/datacontract/datacontract-cli/blob/988a4c88e969452b801ddcfe5c9877deb88d5ad3/datacontract/export/sql_type_converter.py#L231

Timestamp is a valid duckdb type but as of yet there is no converter for it.

**Comment by RobertLD** [comment] 2024-10-18 18:07
@jochenchrist Hey, I'd like your thoughts on this. This is currently a blocker for our project. I wanted to be sure I wasn't making a mistake.

The default duckdb convertion when reading a parquet does not account for timestamp types correctly it would appear.

```
      end_dtutc:
        $ref: "#/definitions/end_dtutc"
        required: true
        type: timestamp_ntz
```
![image](https://github.com/user-attachments/assets/9ed334a5-8e99-4d58-b351-0d157be7856d)

**Comment by jochenchrist** [comment] 2024-10-18 18:10
what server type are you using?

**Comment by RobertLD** [comment] 2024-10-18 18:24
> what server type are you using? S3 with parquet?

servers:
  local_data:
    type: local
    path: trading_strategies.parquet
    format: parquet


the file is read from duckdb, saved as parquet and then validated at a later step

**Comment by jochenchrist** [comment] 2024-10-18 18:48
Looks like a bug. Do you have the possibility to reproduce this in a unit test and possibly create a PR to resolve the problem?

**Comment by RobertLD** [comment] 2024-10-18 19:46
I'd be more than happy to

**Comment by RobertLD** [comment] 2024-10-18 22:13
https://github.com/datacontract/datacontract-cli/pull/473 PR here

**Comment by RobertLD** [comment] 2024-10-18 22:13
> > what server type are you using? S3 with parquet?
> 
> ```
> servers:
>   local_data:
>     type: local
>     path: trading_strategies.parquet
>     format: parquet
> ```
> 
> the file is read from duckdb, saved as parquet and then validated at a later step

PR here -> https://github.com/datacontract/datacontract-cli/pull/473

**Comment by jochenchrist** [comment] 2024-10-26 06:58
resolved with #473

**Closed by jochenchrist** 2024-10-26 06:58 UTC

**Comment by RobertLD** [comment] 2024-10-26 18:55
Thank you for picking up on this, been a busy week! Huge benefit for me
using the library with this fix inplace

**Comment by jochenchrist** [comment] 2024-10-26 20:01
I just release `v0.10.14`

**Comment by RobertLD** [comment] 2024-10-27 19:23
Awesome! In the meantime I'll see about getting import from parquet setup
